import os
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path
from concurrent.futures import ThreadPoolExecutor
ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "scripts"))
from build_html_engine import extract
from build_user_sdk import extract_wapcaplet
from build_user_program import find_zig


class CssEngineTests(unittest.TestCase):
    def test_real_cascade_layout_scene(self):
        with tempfile.TemporaryDirectory(prefix="reist-css-host-") as directory:
            directory = Path(directory)
            roots = extract(directory, css=True)
            roots.append(extract_wapcaplet(directory / "wapcaplet"))
            symbols = ("malloc calloc realloc free memcpy memmove memset memcmp "
                       "memchr strlen strcmp strncmp strchr strrchr strncpy bsearch tolower strncasecmp strdup abs").split()
            command = [str(find_zig()), "cc", "-std=c11", "-O1", "-fno-builtin", "-DNDEBUG",
                       "-DWITHOUT_ICONV_FILTER", "-D_ALIGNED=__attribute__((aligned))",
                       *["-D"+n+"=r310_"+n for n in symbols]]
            for include in (ROOT, ROOT / "userspace/libc/include", ROOT / "userspace/gui/include",
                            ROOT / "userspace/sdk/include"):
                command.append("-I" + str(include))
            for root in roots:
                command += ["-I" + str(root / "include")]
            environment = os.environ.copy()
            environment["ZIG_GLOBAL_CACHE_DIR"] = str(ROOT / "build/codex-agent/css-host-cache")
            environment["ZIG_LOCAL_CACHE_DIR"] = str(directory / "cache")
            jobs, objects = [], []
            for root in roots:
                for source in sorted((root / "src").rglob("*.c")):
                    if source.name.startswith("autogenerated-") or source.name == "css_property_parser_gen.c":
                        continue
                    obj = directory / ("vendor" + str(len(objects)) + ".o")
                    # Each upstream has its own internal utils/ and charset/
                    # headers. Never mix those private include namespaces.
                    jobs.append([*command, "-I"+str(root / "src"), "-c", str(source), "-o", str(obj)])
                    objects.append(obj)
            def compile_one(args):
                result = subprocess.run(args, env=environment,capture_output=True,text=True,timeout=60)
                self.assertEqual(result.returncode,0,result.stderr)
            with ThreadPoolExecutor(max_workers=4) as pool:
                list(pool.map(compile_one,jobs))
            sources = [ROOT / name for name in ("test/test_css_engine_host.c",
                "userspace/libc/lib/bytes.c", "userspace/libc/lib/heap.c",
                "userspace/gui/apps/browser/html_engine.c", "userspace/gui/apps/browser/css_engine.c",
                "userspace/gui/apps/browser/browser_forms.c",
                "userspace/gui/apps/browser/browser_scene.c", "userspace/gui/apps/browser/html_protocol.c",
                "userspace/gui/apps/browser/browser_resources.c", "userspace/programs/curl_http.c",
                "userspace/gui/lib/html_document.c", "userspace/gui/lib/font.c")]
            executable = directory / "css-host.exe"
            response = directory / "compile.rsp"
            response.write_text("\n".join('"' + str(arg).replace('\\', '/') + '"'
                for arg in [*command[2:], *sources, *objects, "-o", executable]), encoding="utf-8")
            result = subprocess.run([*command[:2], "@" + str(response)],
                env=environment, capture_output=True, text=True, timeout=120)
            self.assertEqual(result.returncode,0,result.stderr)
            for mode in ("forms-fixture", "forms", "cascade", "geometry", "quota", "resources", "import", "worker", "bad-packet",
                         "worker-eacces", "worker-missing", "worker-missing-eacces",
                         "worker-revoked", "worker-revoked-eacces", "worker-sleep-failure",
                         "resources-needed", "resources-cascade", "resources-cycle", "resources-depth",
                         "bundle-worker-needs", "bundle-worker-scene", "bundle-worker-offset", "bundle-worker-oom",
                         "chain-eight", "chain-overflow", "worker-buffer-oom", "worker-buffer-deadline"):
                with self.subTest(mode=mode):
                    result = subprocess.run([str(executable),mode], capture_output=True,text=True,timeout=10)
                    self.assertEqual(result.returncode,0,result.stdout+result.stderr)
                    self.assertIn("CSS_CASCADE_SCENE_OK", result.stdout)


if __name__ == "__main__":
    unittest.main()
