import os
import subprocess
import sys
import tempfile
import unittest
import time
from pathlib import Path
from concurrent.futures import ThreadPoolExecutor
ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "scripts"))
from build_html_engine import extract
from build_user_sdk import extract_wapcaplet
from build_user_program import find_zig, cpp_compile_flags
from measure_cpp_baseline import suppress_windows_test_dialogs
from build_browser_fonts import extract as extract_fonts, flags as font_flags, sources as font_sources
DIAGNOSTIC = "--public-diagnostic" in sys.argv
if DIAGNOSTIC:
    sys.argv.remove("--public-diagnostic")


class CssEngineTests(unittest.TestCase):
    def compile_host(self, directory, optimization="-O1", layout=False):
        if True:  # Common bounded build, also used by the O0/O2 layout gate.
            directory = Path(directory)
            roots = extract(directory, css=True)
            roots.append(extract_wapcaplet(directory / "wapcaplet"))
            font_root,_=extract_fonts(directory/'fonts')
            symbols = ("malloc calloc realloc free memcpy memmove memset memcmp "
                       "memchr strlen strcmp strncmp strchr strrchr strncpy bsearch tolower strncasecmp strdup abs").split()
            command = [str(find_zig()), "cc", "-std=c11", optimization, "-fno-builtin", "-DNDEBUG",
                       "-DWITHOUT_ICONV_FILTER", "-D_ALIGNED=__attribute__((aligned))",
                       *["-D"+n+"=r310_"+n for n in symbols]]
            if layout:
                command.append("-DBROWSER_LAYOUT_HOST")
            for include in (ROOT, ROOT / "userspace/libc/include", ROOT / "userspace/gui/include",
                            ROOT / "userspace/sdk/include"):
                command.append("-I" + str(include))
            for root in roots:
                command += ["-I" + str(root / "include")]
            command += ["-I"+str(font_root/'include')]
            environment = os.environ.copy()
            environment["ZIG_GLOBAL_CACHE_DIR"] = str(ROOT / "build/codex-agent/css-host-cache")
            environment["ZIG_LOCAL_CACHE_DIR"] = str(directory / "cache")
            jobs, objects = [], []
            for root in roots:
                for source in sorted((root / "src").rglob("*.c")):
                    if source.name.startswith("autogenerated-") or source.name == "css_property_parser_gen.c":
                        continue
                    obj = directory / ("vendor" + str(len(objects)) + ".o")
                    # Each upstream has its own internal utils/ and charset/
                    # headers. Never mix those private include namespaces.
                    jobs.append([*command, "-I"+str(root / "src"), "-c", str(source), "-o", str(obj)])
                    objects.append(obj)
            def compile_one(args):
                result = subprocess.run(args, env=environment,capture_output=True,text=True,timeout=60)
                self.assertEqual(result.returncode,0,result.stderr)
            for source in font_sources(font_root):
                obj=directory/("vendor-font"+str(len(objects))+".o")
                jobs.append([*command,*font_flags(font_root),"-c",str(source),"-o",str(obj)])
                objects.append(obj)
            with ThreadPoolExecutor(max_workers=4) as pool:
                list(pool.map(compile_one,jobs))
            sources = [ROOT / name for name in ("test/test_css_engine_host.c",
                "userspace/libc/lib/bytes.c", "userspace/libc/lib/heap.c",
                "userspace/gui/apps/browser/html_engine.c", "userspace/gui/apps/browser/script_protocol.c", "userspace/gui/apps/browser/css_engine.c",
                "userspace/gui/apps/browser/browser_forms.c",
                "userspace/gui/apps/browser/browser_scene.c", "userspace/gui/apps/browser/html_protocol.c",
                "userspace/programs/curl_http.c",
                "userspace/gui/lib/html_document.c", "userspace/gui/lib/font.c")]
            executable = directory / "css-host.exe"
            # One migrated TU, all upstream/host/worker sources remain C. Share
            # the original 120-second compile/link budget and symbol adapters.
            deadline = time.monotonic() + 120
            cpp_sources=["userspace/gui/apps/browser/browser_resources.cpp",
                         "userspace/gui/apps/browser/css_values.cpp",
                         "userspace/gui/apps/browser/css_layout.cpp",
                         "userspace/gui/apps/browser/font_engine.cpp"]
            if layout:
                cpp_sources.append("test/browser_layout_host.cpp")
            for name in cpp_sources:
                obj = directory / (Path(name).stem+"-cpp.o")
                result = subprocess.run([*command[:2], *cpp_compile_flags(), *command[3:],
                    "-I"+str(ROOT / "userspace/cpp/include"), "-c", str(ROOT/name), "-o", str(obj)],
                    cwd=ROOT, env=environment, capture_output=True, text=True,
                    timeout=max(.01, deadline-time.monotonic()))
                self.assertEqual(result.returncode,0,result.stderr)
                objects.append(obj)
            response = directory / "compile.rsp"
            response.write_text("\n".join('"' + str(arg).replace('\\', '/') + '"'
                for arg in [*command[2:], *sources, *objects, "-o", executable]), encoding="utf-8")
            result = subprocess.run([*command[:2], "@" + str(response)],
                env=environment, capture_output=True, text=True, timeout=max(.01, deadline-time.monotonic()))
            self.assertEqual(result.returncode,0,result.stderr)
            return executable

    def test_real_cascade_layout_scene(self):
        suppress_windows_test_dialogs()
        with tempfile.TemporaryDirectory(prefix="reist-css-host-") as directory:
            executable = self.compile_host(Path(directory))
            if DIAGNOSTIC:
                for args in (("public-document",), ("public-meta",),
                             ("public-file", ROOT / "build/codex-agent/browser-intracom.html", ROOT / "build/codex-agent/browser-intracom.css"),
                             ("public-file", ROOT / "build/codex-agent/browser-google.html")):
                    result = subprocess.run([str(executable), *map(str,args)], capture_output=True,text=True,timeout=10)
                    print(args[0], "exit=", result.returncode, result.stdout, result.stderr, flush=True)
                    self.assertEqual(result.returncode,0,result.stdout+result.stderr)
                return
            for mode in ("native-controls", "public-document", "public-meta", "public-utf8-bom", "public-transport", "public-utf16", "public-opaque", "public-oom", "forms-fixture", "forms", "cascade", "geometry", "quota", "resources", "import", "worker", "bad-packet",
                         "worker-eacces", "worker-missing", "worker-missing-eacces",
                         "worker-revoked", "worker-revoked-eacces", "worker-sleep-failure",
                         "resources-needed", "resources-cascade", "resources-cycle", "resources-depth",
                         "bundle-worker-needs", "bundle-worker-scene", "bundle-worker-offset", "bundle-worker-oom",
                         "chain-eight", "chain-overflow", "worker-buffer-oom", "worker-buffer-deadline"):
                with self.subTest(mode=mode):
                    result = subprocess.run([str(executable),mode], capture_output=True,text=True,timeout=10)
                    self.assertEqual(result.returncode,0,result.stdout+result.stderr)
                    self.assertIn("CSS_CASCADE_SCENE_OK", result.stdout)


def build_css_host(case, directory, optimization, layout=False):
    return CssEngineTests.compile_host(case, directory, optimization, layout)


if __name__ == "__main__":
    unittest.main()
