import os
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "scripts"))
from build_html_engine import extract
from build_user_program import find_zig


class HtmlEngineTests(unittest.TestCase):
    def test_real_html5_tree_projection(self):
        with tempfile.TemporaryDirectory(prefix="reist-html-host-") as tmp:
            tmp = Path(tmp)
            roots = extract(tmp)
            symbols = ("malloc calloc realloc free memcpy memmove memset memcmp "
                       "memchr strlen strcmp strncmp strchr strrchr strncpy bsearch tolower strncasecmp").split()
            command = [str(find_zig()), "cc", "-std=c11", "-O1", "-fno-builtin", "-DNDEBUG",
                       "-DWITHOUT_ICONV_FILTER", *["-D" + n + "=r39_" + n for n in symbols],
                       "-I" + str(ROOT), "-I" + str(ROOT / "userspace/libc/include"),
                       "-I" + str(ROOT / "userspace/gui/include")]
            command += ["-I" + str(ROOT / "userspace/sdk/include")]
            for root in roots:
                command.extend(["-I" + str(root / "include"), "-I" + str(root / "src")])
            sources = []
            for root in roots:
                sources += sorted(p for p in (root / "src").rglob("*.c") if not p.name.startswith("autogenerated-"))
            sources += [ROOT / p for p in ("test/test_html_engine_host.c", "userspace/libc/lib/bytes.c",
                "userspace/libc/lib/heap.c", "userspace/gui/apps/browser/html_engine.c",
                "userspace/gui/apps/browser/html_protocol.c", "userspace/gui/lib/html_document.c")]
            executable = tmp / "html-host.exe"
            env = os.environ.copy()
            env["ZIG_GLOBAL_CACHE_DIR"] = str(ROOT / "build/codex-agent/html-host-cache")
            env["ZIG_LOCAL_CACHE_DIR"] = str(tmp / "cache")
            compiled = subprocess.run([*command, *map(str, sources), "-o", str(executable)],
                                      cwd=ROOT, env=env, capture_output=True, text=True, timeout=120)
            self.assertEqual(compiled.returncode, 0, compiled.stderr)
            result = subprocess.run([str(executable)], capture_output=True, text=True, timeout=10)
            self.assertEqual(result.returncode, 0, result.stdout + result.stderr)
            self.assertIn("HTML5_TREE_PROJECTION_OK", result.stdout)
            for case in ("quota", "worker", "bad-request", "truncated", "extra", "write-fail", "fixture", "charset"):
                with self.subTest(case=case):
                    result = subprocess.run([str(executable), case], capture_output=True, text=True, timeout=10)
                    self.assertEqual(result.returncode, 0, result.stdout + result.stderr)
                    self.assertIn("HTML5_", result.stdout)
                    if case == "fixture":
                        print(result.stdout.strip())


if __name__ == "__main__":
    unittest.main()
