/**
 * @file include/reist/abi/syscall.h
 * @brief Authoritative append-only REIST syscall ABI.
 *
 * The three fields are the legacy Kernel name, public SDK name and immutable
 * numeric index.  Compatibility projections are generated from this list.
 */
#ifndef REIST_ABI_SYSCALL_H
#define REIST_ABI_SYSCALL_H

#define REIST_SYSCALL_ABI_VERSION 1U
#define REIST_SYSCALL_COUNT 120U

#define REIST_SYSCALL_LIST(X) \
    X(TERMINAL_PUTCHAR, PUTCHAR, 0U) \
    X(PRINT, PRINT_NUMBER, 1U) \
    X(DELAY, DELAY, 2U) \
    X(WAIT_ENTER, WAIT_ENTER, 3U) \
    X(MALLOC, MALLOC, 4U) \
    X(FREE, FREE, 5U) \
    X(REALLOC, REALLOC, 6U) \
    X(TERMINAL_GETCHAR, GETCHAR, 7U) \
    X(INSTALL_IRQ, RESERVED_INSTALL_IRQ, 8U) \
    X(EXIT, EXIT, 9U) \
    X(GET_DATE, GET_DATE, 10U) \
    X(GET_TIME, GET_TIME, 11U) \
    X(UPTIME_MS, UPTIME_MS, 12U) \
    X(MEMORY_KB, MEMORY_KB, 13U) \
    X(OPEN, OPEN, 14U) \
    X(READ, READ, 15U) \
    X(CLOSE, CLOSE, 16U) \
    X(STAT, STAT, 17U) \
    X(READDIR, READDIR, 18U) \
    X(CREATE, CREATE, 19U) \
    X(WRITE, WRITE, 20U) \
    X(UNLINK, UNLINK, 21U) \
    X(GETPID, GETPID, 22U) \
    X(SPAWN, SPAWN, 23U) \
    X(WAIT, WAIT, 24U) \
    X(READDIR_BATCH, READDIR_BATCH, 25U) \
    X(PROCESS_INFO, PROCESS_INFO, 26U) \
    X(KILL, KILL, 27U) \
    X(GETCWD, GETCWD, 28U) \
    X(CHDIR, CHDIR, 29U) \
    X(SPAWNV, SPAWNV, 30U) \
    X(DRIVE_INFO, DRIVE_INFO, 31U) \
    X(SPACE, SPACE, 32U) \
    X(MKDIR, MKDIR, 33U) \
    X(RMDIR, RMDIR, 34U) \
    X(CLEAR, CLEAR, 35U) \
    X(SET_CURSOR, SET_CURSOR, 36U) \
    X(TERMINAL_WRITE, TERMINAL_WRITE, 37U) \
    X(TERMINAL_DRAW, TERMINAL_DRAW, 38U) \
    X(GETCHAR_NONBLOCKING, GETCHAR_NONBLOCKING, 39U) \
    X(YIELD, YIELD, 40U) \
    X(SLEEP_MS, SLEEP_MS, 41U) \
    X(MONOTONIC_MS, MONOTONIC_MS, 42U) \
    X(MEMORY_STATS, MEMORY_STATS, 43U) \
    X(DISPLAY_INFO, DISPLAY_INFO, 44U) \
    X(FILL_RECT, FILL_RECT, 45U) \
    X(DRAW_TEXT, DRAW_TEXT, 46U) \
    X(RENAME, RENAME, 47U) \
    X(FSYNC, FSYNC, 48U) \
    X(IPC_CREATE, IPC_CREATE, 49U) \
    X(IPC_SEND, IPC_SEND, 50U) \
    X(IPC_RECEIVE, IPC_RECEIVE, 51U) \
    X(IPC_CLOSE, IPC_CLOSE, 52U) \
    X(IPC_SEND_TIMEOUT, IPC_SEND_TIMEOUT, 53U) \
    X(IPC_RECEIVE_TIMEOUT, IPC_RECEIVE_TIMEOUT, 54U) \
    X(IPC_DELEGATE, IPC_DELEGATE, 55U) \
    X(REIST_REPORT, REIST_REPORT, 56U) \
    X(SERVICE_CONNECT, SERVICE_CONNECT, 57U) \
    X(IPC_RELEASE, IPC_RELEASE, 58U) \
    X(NETWORK_PROBE, NETWORK_PROBE, 59U) \
    X(NETWORK_PROBE_ID, NETWORK_PROBE_ID, 60U) \
    X(NETWORK_PROBE_STATS, NETWORK_PROBE_STATS, 61U) \
    X(REIST_ARP_BINDING, REIST_ARP_BINDING, 62U) \
    X(REIST_ARP_REPLY, REIST_ARP_REPLY, 63U) \
    X(REIST_ARP_RESOLUTION, REIST_ARP_RESOLUTION, 64U) \
    X(NETWORK_ARP_RESOLVE, NETWORK_ARP_RESOLVE, 65U) \
    X(STORAGE_BIND, STORAGE_BIND, 66U) \
    X(STORAGE_SUBMIT, STORAGE_SUBMIT, 67U) \
    X(STORAGE_CLAIM, STORAGE_CLAIM, 68U) \
    X(STORAGE_BLOCK_READ, STORAGE_BLOCK_READ, 69U) \
    X(STORAGE_COMPLETE, STORAGE_COMPLETE, 70U) \
    X(STORAGE_COLLECT, STORAGE_COLLECT, 71U) \
    X(REIST_ICMP_ECHO_REPLY, REIST_ICMP_ECHO_REPLY, 72U) \
    X(REIST_DHCP_COMMIT, REIST_DHCP_COMMIT, 73U) \
    X(REIST_UDP_ECHO_REPLY, REIST_UDP_ECHO_REPLY, 74U) \
    X(REIST_UDP_BIND, REIST_UDP_BIND, 75U) \
    X(REIST_UDP_UNBIND, REIST_UDP_UNBIND, 76U) \
    X(REIST_UDP_REPLY, REIST_UDP_REPLY, 77U) \
    X(REIST_DHCP_RENEW, REIST_DHCP_RENEW, 78U) \
    X(REIST_NETWORK_FRAME, REIST_NETWORK_FRAME, 79U) \
    X(REIST_UDP_INGRESS, REIST_UDP_INGRESS, 80U) \
    X(REIST_DHCP_INGRESS, REIST_DHCP_INGRESS, 81U) \
    X(REIST_DHCP_BOOT_START, REIST_DHCP_BOOT_START, 82U) \
    X(REIST_ICMP_INGRESS, REIST_ICMP_INGRESS, 83U) \
    X(SCHEDULER_STATS, SCHEDULER_STATS, 84U) \
    X(STORAGE_BLOCK_WRITE, STORAGE_BLOCK_WRITE, 85U) \
    X(STORAGE_MAINT_ACQUIRE, STORAGE_MAINT_ACQUIRE, 86U) \
    X(STORAGE_MAINT_RENEW, STORAGE_MAINT_RENEW, 87U) \
    X(STORAGE_MAINT_RELEASE, STORAGE_MAINT_RELEASE, 88U) \
    X(DRIVE_STATUS, DRIVE_STATUS, 89U) \
    X(ADMIN_STORAGE, ADMIN_STORAGE, 90U) \
    X(COMPONENT_CONTROL, COMPONENT_CONTROL, 91U) \
    X(PARTITION_CREATE, PARTITION_CREATE, 92U) \
    X(STORAGE_BLOCK_FLUSH, STORAGE_BLOCK_FLUSH, 93U) \
    X(STORAGE_MEDIA_COMMIT, STORAGE_MEDIA_COMMIT, 94U) \
    X(STORAGE_FORMAT_PROBE, STORAGE_FORMAT_PROBE, 95U) \
    X(NETWORK_CONTROL, NETWORK_CONTROL, 96U) \
    X(UDP_SOCKET_CONTROL, UDP_SOCKET_CONTROL, 97U) \
    X(UDP_SOCKET_SENDTO, UDP_SOCKET_SENDTO, 98U) \
    X(UDP_SOCKET_RECVFROM, UDP_SOCKET_RECVFROM, 99U) \
    X(UDP_SOCKET_INGRESS, UDP_SOCKET_INGRESS, 100U) \
    X(TCP_SOCKET_CONTROL, TCP_SOCKET_CONTROL, 101U) \
    X(TCP_SOCKET_CONNECT, TCP_SOCKET_CONNECT, 102U) \
    X(TCP_SOCKET_SEND, TCP_SOCKET_SEND, 103U) \
    X(TCP_SOCKET_RECEIVE, TCP_SOCKET_RECEIVE, 104U) \
    X(TCP_SOCKET_INGRESS, TCP_SOCKET_INGRESS, 105U) \
    X(TCP_SOCKET_LISTEN, TCP_SOCKET_LISTEN, 106U) \
    X(TCP_SOCKET_ACCEPT, TCP_SOCKET_ACCEPT, 107U) \
    X(TOUCH, TOUCH, 108U) \
    X(DISPLAY_CONTROL, DISPLAY_CONTROL, 109U) \
    X(MOUSE_EVENT, MOUSE_EVENT, 110U) \
    X(POINTER_UPDATE, POINTER_UPDATE, 111U) \
    X(USB_DIAGNOSTICS, USB_DIAGNOSTICS, 112U) \
    X(DEVICE_CONTROL, DEVICE_CONTROL, 113U) \
    X(PROCESS_IDENTITY, PROCESS_IDENTITY, 114U) \
    X(DRAW_TEXT_CLIPPED, DRAW_TEXT_CLIPPED, 115U) \
    X(RUNTIME_TIMING, RUNTIME_TIMING, 116U) \
    X(BOOT_STATUS, BOOT_STATUS, 117U) \
    X(STORAGE_CANCEL, STORAGE_CANCEL, 118U) \
    X(STORAGE_CLAIM_IDENTITY, STORAGE_CLAIM_IDENTITY, 119U)

#define REIST_DECLARE_SYSCALL(kernel_name, sdk_name, number) \
    REIST_SYS_##sdk_name = number,
typedef enum {
    REIST_SYSCALL_LIST(REIST_DECLARE_SYSCALL)
} reist_syscall_number_t;
#undef REIST_DECLARE_SYSCALL

/* Positive POSIX errno values; syscall failures return their negation. */
typedef enum {
    REIST_EPERM = 1,
    REIST_ENOENT = 2,
    REIST_EIO = 5,
    REIST_EBADF = 9,
    REIST_EAGAIN = 11,
    REIST_ENOMEM = 12,
    REIST_EACCES = 13,
    REIST_EFAULT = 14,
    REIST_EBUSY = 16,
    REIST_EEXIST = 17,
    REIST_ENODEV = 19,
    REIST_EINVAL = 22,
    REIST_EMFILE = 24,
    REIST_ENOSPC = 28,
    REIST_EROFS = 30,
    REIST_ERANGE = 34,
    REIST_ENAMETOOLONG = 36,
    REIST_EOVERFLOW = 75,
    REIST_ENOTSUP = 95,
    REIST_ETIMEDOUT = 110,
    REIST_ESTALE = 116,
} reist_errno_t;

#endif
