# REIST desktop file associations
schema=reist.filetypes/1
.txt=/usr/gui/bin/notepad.prg
.log=/usr/gui/bin/notepad.prg
.conf=/usr/gui/bin/notepad.prg
.md=/usr/gui/bin/notepad.prg
.html=/usr/gui/bin/browser.prg
.htm=/usr/gui/bin/browser.prg
.wav=/usr/gui/bin/soundplayer.prg
.bmp=/usr/gui/bin/imageviewer.prg
.gif=/usr/gui/bin/imageviewer.prg
