"""Pinned NetSurf parser build. No network fetch, host libc or debug stdio."""
from pathlib import Path, PurePosixPath
import hashlib
import os
import shutil
import subprocess
import tarfile
import tempfile

ROOT = Path(__file__).resolve().parents[1]
PINS = {
    "libparserutils": ("0.2.5", "317ed5c718f17927b5721974bae5de32c3fd6d055db131ad31b4312a032ed139"),
    "libhubbub": ("0.3.8", "8ac1e6f5f3d48c05141d59391719534290c59cd029efc249eb4fdbac102cd5a5"),
}


def extract(destination):
    roots = []
    for name, (version, digest) in PINS.items():
        packed = ROOT / "third_party" / (name + ".tar.gz")
        pin = ROOT / "third_party" / (name + ".sha256")
        if hashlib.sha256(packed.read_bytes()).hexdigest() != digest or pin.read_text().split()[0] != digest:
            raise ValueError(f"{name}: archive pin mismatch")
        root = destination / name
        total = 0
        with tarfile.open(packed, "r:gz") as archive:
            for member in archive:
                parts = PurePosixPath(member.name).parts
                if not parts or parts[0] != f"{name}-{version}" or ".." in parts:
                    raise ValueError("invalid parser archive path")
                relative = PurePosixPath(*parts[1:])
                if member.isdir():
                    continue
                if str(relative) not in ("COPYING", "build/Aliases", "build/Entities", "build/make-aliases.pl", "build/make-entities.pl") and not (
                        parts[1] in ("src", "include") and relative.suffix in (".c", ".h", ".inc", ".gperf")):
                    continue
                if not member.isfile() or member.size > 4 * 1024 * 1024:
                    raise ValueError("invalid parser archive member")
                total += member.size
                if total > 8 * 1024 * 1024:
                    raise ValueError("parser archive extraction quota")
                data = archive.extractfile(member).read()
                # All stdio consumers are upstream debug-only code. NDEBUG is
                # mandatory; removing the otherwise unused includes grants no
                # fake FILE/API and changes no parser algorithm or table bytes.
                if relative.suffix in (".c", ".h"):
                    data = data.replace(b"#include <stdio.h>", b"/* REIST: debug stdio excluded (NDEBUG). */")
                    # These libraries use inttypes only for integer typedefs
                    # outside disabled debug printing, not conversion APIs.
                    data = data.replace(b"#include <inttypes.h>", b"#include <stdint.h>")
                target = root.joinpath(*relative.parts)
                target.parent.mkdir(parents=True, exist_ok=True)
                target.write_bytes(data)
        perl = shutil.which("perl") or "C:/msys64/usr/bin/perl.exe"
        generator = "make-aliases.pl" if name == "libparserutils" else "make-entities.pl"
        subprocess.run([perl, "build/" + generator], cwd=root, check=True, timeout=30)
        if name == "libhubbub":
            gperf = shutil.which("gperf") or "C:/msys64/usr/bin/gperf.exe"
            generated = root / "src/treebuilder/autogenerated-element-type.c"
            subprocess.run([gperf, "--output-file=src/treebuilder/autogenerated-element-type.c",
                            "src/treebuilder/element-type.gperf"], cwd=root, check=True, timeout=30)
            data = generated.read_text().replace("\nconst struct element_type_map", "\nstatic const struct element_type_map")
            data = data.replace("#include <inttypes.h>", "#include <stdint.h>")
            generated.write_text(data)
        roots.append(root)
    return roots


def build(artifacts, zig, incremental):
    from build_user_program import freestanding_compile_prefix
    headers = list((ROOT / "userspace/libc/include").rglob("*.h"))
    dependencies = [Path(__file__), *headers]
    for name in PINS:
        dependencies.extend(ROOT / "third_party" / (name + suffix) for suffix in (".tar.gz", ".sha256"))
    outputs = [artifacts.library_dir / "libparserutils.a", artifacts.library_dir / "libhubbub.a"]
    if incremental and all(p.is_file() and all(d.stat().st_mtime_ns <= p.stat().st_mtime_ns for d in dependencies) for p in outputs):
        return
    with tempfile.TemporaryDirectory(prefix="reist-html-build-") as temporary:
        temporary = Path(temporary)
        roots = extract(temporary)
        env = os.environ.copy()
        env["ZIG_GLOBAL_CACHE_DIR"] = str(artifacts.root / "html-cache")
        env["ZIG_LOCAL_CACHE_DIR"] = str(temporary / "cache")
        for root, output in zip(roots, outputs):
            includes = [ROOT / "userspace/libc/include", root / "include", root / "src", roots[0] / "include"]
            prefix = freestanding_compile_prefix(zig, includes)
            objects = []
            for index, source in enumerate(sorted((root / "src").rglob("*.c"))):
                if source.name.startswith("autogenerated-"):
                    continue
                obj = temporary / (root.name + str(index) + ".o")
                subprocess.run([*prefix, "-DWITHOUT_ICONV_FILTER", "-std=c11", "-c", str(source), "-o", str(obj)], env=env, check=True, timeout=60)
                objects.append(obj)
            archive = temporary / output.name
            subprocess.run([str(zig), "ar", "rcs", str(archive), *map(str, objects)], env=env, check=True, timeout=30)
            shutil.copy2(archive, output)
            shutil.copytree(root / "include", artifacts.include_dir, dirs_exist_ok=True)
            license_path = artifacts.root / "usr/share/licenses" / root.name / "COPYING"
            license_path.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(root / "COPYING", license_path)
            version = PINS[root.name][0]
            dependency = "reist-c" if root == roots[0] else "libparserutils"
            pc = ("prefix=${pcfiledir}/../..\nlibdir=${prefix}/lib\nincludedir=${prefix}/include\n"
                  f"Name: {root.name}\nDescription: Bounded REIST NetSurf parser port\nVersion: {version}\n"
                  f"Requires: {dependency}\nCflags: -I${{includedir}}\nLibs: -L${{libdir}} -l{root.name[3:]}\n")
            (artifacts.library_dir / "pkgconfig" / (root.name + ".pc")).write_text(pc, encoding="ascii")
