"""Generate deterministic fixed Unicode 15.0.0 normalization tables."""

from __future__ import annotations

import argparse
from functools import lru_cache
from pathlib import Path
import unicodedata


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_OUTPUT = ROOT / "include/reist/unicode_tables_15_0.h"
UNICODE_VERSION = "15.0.0"
PATH_BYTES = 255


def scalar_values() -> list[int]:
    return [value for value in range(0x110000)
            if not 0xD800 <= value <= 0xDFFF]


def canonical_mapping(value: int) -> tuple[int, ...]:
    description = unicodedata.decomposition(chr(value))
    if not description or description.startswith("<"):
        return ()
    return tuple(int(item, 16) for item in description.split())


@lru_cache(maxsize=None)
def recursive_decomposition(value: int) -> tuple[int, ...]:
    mapping = canonical_mapping(value)
    if not mapping:
        return (value,)
    result: tuple[int, ...] = ()
    for mapped in mapping:
        result += recursive_decomposition(mapped)
    return result


def folded_decomposition(value: int) -> tuple[int, ...]:
    result: tuple[int, ...] = ()
    for character in chr(value).casefold():
        result += recursive_decomposition(ord(character))
    return result


def derive_path_bound(values: list[int], measure) -> int:
    best_by_bytes = [0, 0, 0, 0]
    for value in values:
        encoded = chr(value).encode("utf-8")
        index = len(encoded) - 1
        best_by_bytes[index] = max(best_by_bytes[index], measure(value))
    dynamic = [0] * (PATH_BYTES + 1)
    for capacity in range(1, PATH_BYTES + 1):
        dynamic[capacity] = max(
            dynamic[capacity - width] + best_by_bytes[width - 1]
            for width in range(1, 5) if width <= capacity)
    return dynamic[PATH_BYTES]


def format_values(values: list[int], width: int = 8) -> list[str]:
    lines: list[str] = []
    for start in range(0, len(values), width):
        chunk = values[start:start + width]
        lines.append("    " + ", ".join(f"0x{value:08X}U" for value in chunk) + ",")
    return lines


def generate() -> str:
    if unicodedata.unidata_version != UNICODE_VERSION:
        raise RuntimeError(
            f"Unicode database {UNICODE_VERSION} required, got "
            f"{unicodedata.unidata_version}")
    values = scalar_values()

    decomposition_entries: list[tuple[int, int, int]] = []
    decomposition_data: list[int] = []
    for value in values:
        mapping = canonical_mapping(value)
        if mapping:
            decomposition_entries.append(
                (value, len(decomposition_data), len(mapping)))
            decomposition_data.extend(mapping)

    fold_entries: list[tuple[int, int, int]] = []
    fold_data: list[int] = []
    for value in values:
        mapping = tuple(ord(character) for character in chr(value).casefold())
        if mapping != (value,):
            fold_entries.append((value, len(fold_data), len(mapping)))
            fold_data.extend(mapping)

    combining = [(value, unicodedata.combining(chr(value)))
                 for value in values if unicodedata.combining(chr(value))]

    compositions: list[tuple[int, int, int]] = []
    for value, _, length in decomposition_entries:
        mapping = canonical_mapping(value)
        if length == 2 and unicodedata.normalize(
                "NFC", chr(mapping[0]) + chr(mapping[1])) == chr(value):
            compositions.append((mapping[0], mapping[1], value))
    compositions.sort()

    scalar_bound = derive_path_bound(
        values, lambda value: len(folded_decomposition(value)))
    key_bound = derive_path_bound(
        values, lambda value: len(unicodedata.normalize(
            "NFC", chr(value).casefold()).encode("utf-8")))
    if scalar_bound != 382 or key_bound != 762:
        raise RuntimeError(
            f"Unicode capacity proof drifted: {scalar_bound} scalars, "
            f"{key_bound} bytes")

    lines = [
        "/** Generated by scripts/generate_unicode_tables.py; do not edit. */",
        "#ifndef REIST_UNICODE_TABLES_15_0_H",
        "#define REIST_UNICODE_TABLES_15_0_H",
        "",
        "#include <stdint.h>",
        "",
        f'#define REIST_UNICODE_DATA_VERSION "{UNICODE_VERSION}"',
        f"#define REIST_UNICODE_DECOMPOSED_CAPACITY {scalar_bound}U",
        f"#define REIST_UNICODE_KEY_CAPACITY {key_bound + 1}U",
        "",
        "typedef struct {",
        "    uint32_t scalar;",
        "    uint16_t offset;",
        "    uint8_t length;",
        "} reist_unicode_mapping_t;",
        "",
        "typedef struct {",
        "    uint32_t scalar;",
        "    uint8_t value;",
        "} reist_unicode_ccc_t;",
        "",
        "typedef struct {",
        "    uint32_t starter;",
        "    uint32_t combining;",
        "    uint32_t composed;",
        "} reist_unicode_composition_t;",
        "",
        "static const uint32_t reist_unicode_decomposition_data[] = {",
        *format_values(decomposition_data),
        "};",
        "static const reist_unicode_mapping_t reist_unicode_decompositions[] = {",
    ]
    lines.extend(f"    {{0x{value:06X}U, {offset}U, {length}U}},"
                 for value, offset, length in decomposition_entries)
    lines.extend([
        "};",
        "static const uint32_t reist_unicode_casefold_data[] = {",
        *format_values(fold_data),
        "};",
        "static const reist_unicode_mapping_t reist_unicode_casefolds[] = {",
    ])
    lines.extend(f"    {{0x{value:06X}U, {offset}U, {length}U}},"
                 for value, offset, length in fold_entries)
    lines.extend([
        "};",
        "static const reist_unicode_ccc_t reist_unicode_combining_classes[] = {",
    ])
    lines.extend(f"    {{0x{value:06X}U, {ccc}U}},"
                 for value, ccc in combining)
    lines.extend([
        "};",
        "static const reist_unicode_composition_t reist_unicode_compositions[] = {",
    ])
    lines.extend(f"    {{0x{first:06X}U, 0x{second:06X}U, 0x{result:06X}U}},"
                 for first, second, result in compositions)
    lines.extend([
        "};",
        "",
        "#define REIST_UNICODE_DECOMPOSITION_COUNT \\",
        "    (sizeof(reist_unicode_decompositions) / sizeof(reist_unicode_decompositions[0]))",
        "#define REIST_UNICODE_CASEFOLD_COUNT \\",
        "    (sizeof(reist_unicode_casefolds) / sizeof(reist_unicode_casefolds[0]))",
        "#define REIST_UNICODE_COMBINING_CLASS_COUNT \\",
        "    (sizeof(reist_unicode_combining_classes) / sizeof(reist_unicode_combining_classes[0]))",
        "#define REIST_UNICODE_COMPOSITION_COUNT \\",
        "    (sizeof(reist_unicode_compositions) / sizeof(reist_unicode_compositions[0]))",
        "",
        "#endif",
        "",
    ])
    if len(decomposition_data) > 0xFFFF or len(fold_data) > 0xFFFF:
        raise RuntimeError("16-bit mapping offsets are no longer sufficient")
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--check", action="store_true")
    arguments = parser.parse_args()
    generated = generate()
    if arguments.check:
        if not arguments.output.exists() or arguments.output.read_text(
                encoding="utf-8") != generated:
            raise SystemExit("Unicode table is stale")
        return
    arguments.output.parent.mkdir(parents=True, exist_ok=True)
    arguments.output.write_text(generated, encoding="utf-8", newline="\n")


if __name__ == "__main__":
    main()
