"""Generate the deterministic Unicode-to-IBM-PC CP437 glyph map."""

from __future__ import annotations

import argparse
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_OUTPUT = ROOT / "include/reist/unicode_vga_font.h"

CONTROL_GRAPHICS = {
    0x01: 0x263A, 0x02: 0x263B, 0x03: 0x2665, 0x04: 0x2666,
    0x05: 0x2663, 0x06: 0x2660, 0x07: 0x2022, 0x08: 0x25D8,
    0x09: 0x25CB, 0x0A: 0x25D9, 0x0B: 0x2642, 0x0C: 0x2640,
    0x0D: 0x266A, 0x0E: 0x266B, 0x0F: 0x263C, 0x10: 0x25BA,
    0x11: 0x25C4, 0x12: 0x2195, 0x13: 0x203C, 0x14: 0x00B6,
    0x15: 0x00A7, 0x16: 0x25AC, 0x17: 0x21A8, 0x18: 0x2191,
    0x19: 0x2193, 0x1A: 0x2192, 0x1B: 0x2190, 0x1C: 0x221F,
    0x1D: 0x2194, 0x1E: 0x25B2, 0x1F: 0x25BC, 0x7F: 0x2302,
}


def entries() -> list[tuple[int, int]]:
    mapping = [(scalar, glyph) for glyph, scalar in CONTROL_GRAPHICS.items()]
    for glyph in range(0x80, 0x100):
        scalar = ord(bytes((glyph,)).decode("cp437"))
        mapping.append((scalar, glyph))
    mapping.sort()
    if len(mapping) != 160 or len({scalar for scalar, _ in mapping}) != 160:
        raise RuntimeError("CP437 Unicode keys are not unique")
    return mapping


def generate() -> str:
    mapping = entries()
    lines = [
        "/** Generated by scripts/generate_cp437_unicode.py; do not edit. */",
        "#ifndef REIST_UNICODE_VGA_FONT_H",
        "#define REIST_UNICODE_VGA_FONT_H",
        "",
        "#include <stddef.h>",
        "#include <stdint.h>",
        "",
        "#define REIST_UNICODE_VGA_MISSING_GLYPH 0xFEU",
        "",
        "typedef struct {",
        "    uint32_t scalar;",
        "    uint8_t glyph;",
        "} reist_unicode_vga_mapping_t;",
        "",
        "static const reist_unicode_vga_mapping_t reist_unicode_vga_mappings[] = {",
    ]
    lines.extend(
        f"    {{0x{scalar:06X}U, 0x{glyph:02X}U}},"
        for scalar, glyph in mapping
    )
    lines.extend([
        "};",
        "",
        "#define REIST_UNICODE_VGA_MAPPING_COUNT \\",
        "    (sizeof(reist_unicode_vga_mappings) / \\",
        "     sizeof(reist_unicode_vga_mappings[0]))",
        "",
        "static inline uint8_t reist_unicode_vga_glyph(uint32_t scalar) {",
        "    if (scalar <= 0x7FU) return (uint8_t)scalar;",
        "    size_t low = 0U;",
        "    size_t high = REIST_UNICODE_VGA_MAPPING_COUNT;",
        "    while (low < high) {",
        "        size_t middle = low + (high - low) / 2U;",
        "        if (reist_unicode_vga_mappings[middle].scalar < scalar)",
        "            low = middle + 1U;",
        "        else",
        "            high = middle;",
        "    }",
        "    return low < REIST_UNICODE_VGA_MAPPING_COUNT &&",
        "           reist_unicode_vga_mappings[low].scalar == scalar",
        "        ? reist_unicode_vga_mappings[low].glyph",
        "        : REIST_UNICODE_VGA_MISSING_GLYPH;",
        "}",
        "",
        "#endif",
        "",
    ])
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--check", action="store_true")
    arguments = parser.parse_args()
    generated = generate()
    if arguments.check:
        if (not arguments.output.exists() or
                arguments.output.read_text(encoding="utf-8") != generated):
            raise SystemExit("CP437 Unicode table is stale")
        return
    arguments.output.parent.mkdir(parents=True, exist_ok=True)
    arguments.output.write_text(generated, encoding="utf-8", newline="\n")


if __name__ == "__main__":
    main()
